apiVersion: v1
description: A Helm chart for CassKop - the Orange Cassandra Kubernetes operator
name: cassandra-operator
home: https://github.com/Orange-OpenSource/casskop
sources:
  - https://github.com/Orange-OpenSource/casskop
version: 0.0.3
appVersion: 0.0.3-release
maintainers:
  - name: cscetbon
    email: cscetbon@gmail.com
  - name: fdehay
    email: franck.dehay@orange.com
keywords:
- operator
- cassandra
- casskop
