apiVersion: v1
description: A Helm chart for CassKop - the Orange Cassandra Kubernetes operator
name: casskop
home: https://github.com/cscetbon/casskop
sources:
  - https://github.com/cscetbon/casskop
version: 2.1.0
appVersion: 2.1.0-release
maintainers:
  - name: cscetbon
    email: cscetbon@gmail.com
  - name: fdehay
    email: franck.dehay@orange.com
keywords:
- operator
- cassandra
- casskop
