# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: default-deny
# spec:
#   podSelector: {}
#   policyTypes:
#   - Ingress
#   - Egress
# ---
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: cassandra-intra-nodes
# spec:
#   podSelector:
#     matchLabels:
#       app: cassandracluster
#   ingress:
#     - from:
#       - namespaceSelector:
#           matchLabels:
#             app: cassandra-e2e
#         podSelector:
#           matchLabels:
#             app: cassandracluster
#       - namespaceSelector:
#           matchLabels:
#             app: cassandra-e2e
#         podSelector:
#           matchLabels:
#             app: cassandra-stress
#     - ports:
#         - protocol: TCP
#           port: 7000
#         - protocol: TCP
#           port: 7001
#         - protocol: TCP
#           port: 9042
#   egress:
#   - ports:
#     - protocol: TCP
#       port: 7000
#     - protocol: TCP
#       port: 7001
#     - protocol: TCP
#       port: 9042
# ---
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: cassandra-stress-egress
# spec:
#   podSelector:
#     matchLabels:
#       app: cassandra-stress
#   egress:
#   - ports:
#     - protocol: TCP
#       port: 9042
# ---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: casskop-egress-jolokia
spec:
  podSelector:
    matchLabels:
      app: cassandra-operator
  egress:
  - ports:
    - port: 8778
      protocol: TCP
      
# ---
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: cassandra-ingress-jolokia-from-casskop
# spec:
#   podSelector:
#     matchLabels:
#       app: cassandracluster
#   ingress:
#     - from:
#       # - namespaceSelector:
#       #     matchLabels:
#       #       app: cassandra
#       #   podSelector:
#       #     matchLabels:
#       #       app: cassandra-operator
#       - podSelector:
#         namespaceSelector:
#     - ports:
#         - port: 8778
#           protocol: TCP
# ---
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: cassandra-ingress-cqlsh-from-toolbox
# spec:
#   podSelector:
#     matchLabels:
#       app: cassandracluster
#   ingress:
#     - from:
#       - namespaceSelector:
#           matchLabels:
#             app: cassandra-e2e
#         podSelector:
#           matchLabels:
#             app: toolbox
#     - ports:
#         - protocol: TCP
#           port: 9042
# ---
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: toolbox-egress-cqlsh
# spec:
#   podSelector:
#     matchLabels:
#       app: toolbox
#   egress:
#   - ports:
#     - protocol: TCP
#       port: 9042