name: Deploy to GitHub Pages

on:
  pull_request:
  workflow_dispatch:
  push:

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14.13.1
          cache: yarn
          cache-dependency-path: website/yarn.lock

      - name: Build website
        working-directory: website
        run: |
          yarn install --frozen-lockfile --non-interactive --cache-folder ~/.cache/yarn
          yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: website/build