name: golangci-lint

on:
  pull_request:
  push:
    branches:
      - master

jobs:

  golangci:
    name: lint
    runs-on: ubuntu-latest
    container: golangci/golangci-lint:v1.45.0
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - run: golangci-lint run