name: Icarus image

on:
  pull_request:
  workflow_dispatch:

jobs:

  build-publish-icarus-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Clone instaclustr/cassandra-operator
        uses: actions/checkout@v3
        with:
          repository: instaclustr/cassandra-operator
        
      - name: Log in to the Container registry
        uses: docker/login-action@v1.14.1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Icarus Docker image using Makefile
        id: build-and-get-tag
        run: |
          set -x
          make -C docker cassandra-sidecar
          echo base_openjre_tag_state=$(docker images base-openjre|awk '!/latest/ && NR>1 {print $2}') >> $GITHUB_ENV
          echo icarus_tag_state=$(docker images instaclustr-icarus|awk '!/latest/ && NR>1 {print $2}') >> $GITHUB_ENV

      - name: Push Icarus Docker image
        uses: docker/build-push-action@v4
        with:
          context: docker/cassandra-sidecar
          tags: |
            ghcr.io/cscetbon/instaclustr-icarus:latest
            ghcr.io/cscetbon/instaclustr-icarus:${{ env.icarus_tag_state }}
          build-args: openjre_image=base-openjre:${{ env.base_openjre_tag_state }}
          push: true
