name: Icarus image

on:
  workflow_dispatch:
    inputs:
      alias:
        description: 'Docker image alias'
        required: true

jobs:

  build-publish-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Clone instaclustr/cassandra-operator
        uses: actions/checkout@v3
        with:
          repository: instaclustr/cassandra-operator
        
      - name: Log in to the Container registry
        uses: docker/login-action@v1.14.1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Icarus Docker image using Makefile
        id: build-and-get-tag
        run: |
          make -C docker cassandra-sidecar
          echo ::set-output name=tag::$(docker images base-openjre|awk '!/latest/ && NR>1 {print $2}')

      - name: Push Icarus Docker image
        uses: docker/build-push-action@v2.10.0
        with:
          context: docker/cassandra-sidecar
          tags: |
            ghcr.io/cscetbon/instaclustr-icarus:latest
            ghcr.io/cscetbon/instaclustr-icarus:${{ github.event.inputs.alias }}
          build-args: openjre_image="base-openjre:${{ steps.build-and-get-tag.outputs.tag }}"
          push: false