name: publish-charts
on:
  push:
    branches:
      - helm
    # tags: '*'

jobs:
  publish-charts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # - name: Configure Git
      #   run: |
      #     git config user.name "$GITHUB_ACTOR"
      #     git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      # - name: Install Helm
      #   uses: azure/setup-helm@v1
      #   with:
      #     version: v3.7.1

      - name: Publish Helm Casskop charts
        uses: helm/chart-releaser-action@v1.3.0
        with:
          charts_dir: charts
          charts_repo_url: https://${{github.repository_owner}}.github.io/casskop/helm
        env:
          CR_TOKEN: ${{ secrets.GH_TOKEN }}
