name: Publish Helm charts
on:
  push:
    tags: ["*"]

jobs:
  publish-helm-charts:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        chart:
          - casskop
          - multi-casskop

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Overwrite versions in chart before publishing it
        run: |
          sed -i -e "s/1.0.0/${{ github.ref_name }}/" charts/${{ matrix.chart }}/*.yaml

      - name: Publish ${{ matrix.chart }} chart
        uses: appany/helm-oci-chart-releaser@v0.3.0
        with:
          name: ${{ matrix.chart }}-helm
          path: charts/${{ matrix.chart }}
          repository: ${{ github.repository_owner }}
          tag: ${{ github.ref_name }}
          registry: ghcr.io
          registry_username: ${{ github.repository_owner }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
